language: ruby
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
before_script:
  - psql -c 'create database qso_test;' -U postgres
rvm:
 - 2.3.0
services:
 - postgresql
addons:
 code_climate:
  repo_token: 
