default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: qso_development

test:
  <<: *default
  database: qso_test

production:
  <<: *default
  host: <%= ENV['RDS_HOST'] %>
  database: <%= ENV['RDS_DATABASE'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
